---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  secretName: harbor-tls
  duration: 8760h  # 1 year
  renewBefore: 720h  # 30 days
  commonName: harbor.jmarcelocarvalho.com
  dnsNames:
    - harbor.jmarcelocarvalho.com
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
