---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-credentials
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-credentials
    template:
      engineVersion: v2
      data:
        harborAdminPassword: "{{ .adminPassword }}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: secret/harbor/admin-password
        property: password
