apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ExternalSecret.yaml

commonLabels:
  app.kubernetes.io/name: harbor
  app.kubernetes.io/part-of: harbor
  app.kubernetes.io/component: secrets
