apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-library
  namespace: music
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    volume.kubernetes.io/selected-node: kube002
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi
