apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-harbor
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: jenkins-harbor
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        registryUrl: "harbor.jmarcelocarvalho.com"
  data:
    - secretKey: username
      remoteRef:
        key: secret/jenkins/harbor
        property: username
    - secretKey: password
      remoteRef:
        key: secret/jenkins/harbor
        property: password
