apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-github
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: jenkins-github
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: secret/jenkins/github
        property: token
