apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-dockerconfig
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-dockerconfig
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "harbor.jmarcelocarvalho.com": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: secret/jenkins/harbor
        property: username
    - secretKey: password
      remoteRef:
        key: secret/jenkins/harbor
        property: password
