---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-postgresql
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-postgresql
    template:
      engineVersion: v2
      data:
        postgres-password: "{{ .dbPassword }}"
        password: "{{ .dbPassword }}"
  data:
    - secretKey: dbPassword
      remoteRef:
        key: secret/netbox/app
        property: db_password
