---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-valkey
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netbox-valkey
    template:
      engineVersion: v2
      data:
        valkey-password: "{{ .cachePassword }}"
  data:
    - secretKey: cachePassword
      remoteRef:
        key: secret/netbox/app
        property: cache_password
