---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media
  namespace: netbox
  annotations:
    # local-path honors this: forces PV provisioning onto a specific node
    volume.kubernetes.io/selected-node: kube003
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
