apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/jmarcelo81/kubernetes_lab.git
    targetRevision: main
    path: manifests/argocd-image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3
