apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=harbor.jmarcelocarvalho.com/library/jenkins-pipeline-test
    argocd-image-updater.argoproj.io/app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^[0-9]+$
    argocd-image-updater.argoproj.io/app.pull-secret: pullsecret:argocd/harbor-image-updater
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: https://github.com/jmarcelo81/kubernetes_lab.git
    targetRevision: main
    path: manifests/pipeline-test
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: pipeline-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
