apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    experimental:
      plugins:
        bouncer:
          moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
          version: v1.4.5
    volumes:
      - name: crowdsec-bouncer-key
        mountPath: /etc/traefik/crowdsec
        type: secret
        secretName: crowdsec-bouncer-key
